### ISSUE TITLE
Cannot read properties of null (reading '__descriptor')

### ISSUE THREAD

**Issue by pietrovismara** [brendan-duncan/webgpu_inspector#15]
I'm using the [webgpu-spd](https://github.com/JolifantoBambla/webgpu-spd) package to generate mip maps via compute. 
Whenever I try to capture the first frame (immediate mode) I get this error:

```
webgpu_inspector.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading '__descriptor')
    at o._captureCommand (webgpu_inspector.js:1:54134)
    at o._recordCommand (webgpu_inspector.js:1:53579)
    at o._postMethodCall (webgpu_inspector.js:1:43036)
    at t.emit (webgpu_inspector.js:1:906)
    at GPUComputePassEncoder.<anonymous> (webgpu_inspector.js:1:12318)
    at GPUComputePassEncoder.setBindGroup (webgpu_inspector.js:1:12051)
    at SPDPass.encode (index.js:575:28)
    at WebGPUSinglePassDownsampler.generateMipmaps (index.js:1064:19)
    at updateMaterialBindGroups (update-material-bind-groups.ts:156:23)
    at run (scheduler.ts:190:24)
```

The error causes the captured frame information to be incomplete.

**Comment by brendan-duncan** [comment]
Thanks for the report, I'll get it fixed soon.

**Comment by brendan-duncan** [comment]
Finally had a chance to get over to this, and it's fixed in git now. I'll do a chrome store update soon.

**Comment by pietrovismara** [comment]
Great thanks, really appreciate how quick you are in solving issues
