### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by erikdubbelboer** [brendan-duncan/webgpu_inspector#2]
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'BufferImageSource'
    |     property '_events' -> object with constructor 'Events'
    |     property 'resize' -> object with constructor 'Array'
    |     ...
    |     property 'context' -> object with constructor 'Texture'
    --- property '_source' closes the circle
    at JSON.stringify (<anonymous>)
    at o._stringifyDescriptor (webgpu_inspector.js:1:49239)
    at o._recordCommand (webgpu_inspector.js:1:50652)
    at o._postMethodCall (webgpu_inspector.js:1:41320)
    at t.emit (webgpu_inspector.js:1:906)
    at GPUDevice.createSampler (webgpu_inspector.js:1:12318)
    at GpuTextureSystem._initSampler (WebGPURenderer-cc3732e7.js:1818:63)
    at GpuTextureSystem.getGpuSampler (WebGPURenderer-cc3732e7.js:1822:59)
    at BindGroupSystem._createBindGroup (WebGPURenderer-cc3732e7.js:105:40)
    at BindGroupSystem.getBindGroup (WebGPURenderer-cc3732e7.js:69:61)
```

This happens when trying to debug anything on https://dubbelboer.com/sillysky/

WebGPU Inspector: `0.0.9`
OS: `MacOS Sonoma 14.4`
Browser: `Chrome 123.0.6312.59 (Official Build) (arm64)`

**Comment by brendan-duncan** [comment]
I have that fixed in the github version. I'll get the Chrome store version updated.

**Comment by brendan-duncan** [comment]
Chrome store update has been requested. Usually takes a day or so for them to publish. Will be version 0.1.0 when they do.

**Comment by brendan-duncan** [comment]
Of course I fix a couple more issues inspecting that game **after**  I submit the chrome store update. Guess I'll have to do another release soon.

**Comment by erikdubbelboer** [comment]
This was fixed 👍 . Didn't get a change to test it earlier.
